In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from collections import Counter
import math
from scipy.stats import norm

#from sklearn.datasets import load_iris


# import dataset
iris = datasets.load_iris()

data = iris.data  
species = iris.target


#split dataset into test set(20%) and train set(80%) using stratify to split into equal size
data_train,data_test,species_train,species_test = train_test_split(data,species, test_size = 0.2, stratify = species,random_state=1)
print(np.bincount(species_train))

newIris = pd.DataFrame(np.column_stack([data_train,species_train]))

#Sort and rearrange the data based on the species
setosa = newIris[newIris[4] == 0]
versicolor = newIris[newIris[4]==1]       
virginica  = newIris[newIris[4]==2] 
newIris = pd.concat([setosa,versicolor,virginica])


#Splits data based on species
setosa_data=newIris[0:40] 
versicolor_data=newIris[40:80]
virginica_data=newIris[80:120]

#find mean
setosa_mean = setosa_data.mean()
versicolor_mean = versicolor_data.mean()
virginica_mean= virginica_data.mean()
 
#find std    
setosa_std = setosa_data.std()
versicolor_std = versicolor_data.std()
virginica_std = virginica_data.std()
    
print("")
x =[]
likelihood = []

#Find Likelihood    
for j in range(len(newIris)):
    distribution = 1
    if(j<40):
        mean=setosa_mean
        std = setosa_std
    if(j>=40 and j<80):
        mean=versicolor_mean
        std = versicolor_std
    if(j>=80 and j<120):
        mean=virginica_mean
        std = virginica_std    
    
    for i in range(4):
        x = newIris.iloc[j] 
        a= ((x[i]- mean[i])**2)/(2*std[i]**2)
        b= math.sqrt(2*math.pi*(std[i]**2))
        y = math.exp(-a)/b
        distribution= distribution*y  
    likelihood.append(distribution)
    x=[]  
print("likelihood")    
print(likelihood)              
print(" ")
            
#Find Priori probability
setosa_priori = len(setosa_data)/len(newIris)
versicolor_priori = len(versicolor_data)/len(newIris)
virginica_priori = len(virginica_data)/len(newIris)
print("Priori Probability")
print(setosa_priori)
print(versicolor_priori)
print(virginica_priori) 



#convert test data into a dataframe
newTest = pd.DataFrame(np.column_stack([data_test,species_test]))

#Rearrange the data into groups based on the species
setosa = newTest[newTest[4] == 0]
versicolor = newTest[newTest[4]==1]       
virginica  = newTest[newTest[4]==2] 
newTest = pd.concat([setosa,versicolor,virginica])

#find likelihood for test data
testLikelihood =[]
x=[]
testPosterior=[]
posteriorSpecies =[]
print()
print("Test Posterior")
for j in range(len(newTest)):
    for c in range(3): 
        if (c==0):
            mean = setosa_mean
            std = setosa_std
            priori = setosa_priori
        if (c == 1):
            mean= versicolor_mean
            std = versicolor_std
            priori = versicolor_priori
        if(c == 2):
            mean= virginica_mean
            std = virginica_std
            priori = virginica_priori
        distribution = 1       
        for i in range(4):
            x = newTest.iloc[j] 
            a= ((x[i]- mean[i])**2)/(2*std[i]**2)
            b= math.sqrt(2*math.pi*(std[i]**2))
            y = math.exp(-a)/b 
            distribution= distribution*y
        x=[]    
        testLikelihood.append(distribution)
        posterior = testLikelihood[c]* priori    #Calculate poterior values
        testPosterior.append(posterior)
        maxPosterior = testPosterior.index(max(testPosterior))   #finds the maximum value
    posteriorSpecies.append(maxPosterior)
    print(testPosterior)
    testLikelihood =[]    
    testPosterior=[] 
    
print("")  
print("Species of original test data") 
species_test = list(map(int,newTest[4]))
print(species_test)
print("Species of Maximum Posterior values")    
print(posteriorSpecies)

#Accuarcy
similar=0
for i in range(len(posteriorSpecies)):
    if(species_test[i] == posteriorSpecies[i]):
        similar +=1
accuracy = similar/(i+1)*100
print("")
print("accuracy")
print(accuracy)

#Challenging Part
samples =[] 
transpose =[]
size = int(input("Enter the number of samples need : "))
for c in range(3):
    if (c==0):
        mean = setosa_mean
        std = setosa_std
        priori = setosa_priori
    if (c == 1):
        mean= versicolor_mean
        std = versicolor_std
        priori = versicolor_priori
    if(c == 2):
        mean= virginica_mean
        std = virginica_std
        priori = virginica_priori
    for i in range(4):  
        
        sample = norm.rvs(loc=mean[i], scale=std[i], size=(size))
        samples.append(sample)
        samples_arr = np.array(samples)
        transpose = samples_arr.transpose()
    print("Category : "+ str(c))    
    print(transpose)
    samples = []    
        
        

[40 40 40]

likelihood
[1.4075931692068417, 4.916023372101059, 3.723785500440289, 0.5667255131169594, 11.224723139042288, 4.762972667133081, 0.9983045256200961, 5.085875557618514, 10.75691698927069, 0.3386062416079456, 2.535662999430496, 5.587653661390406, 0.08139841967700429, 4.480716361534181, 9.300134300230537, 0.06366739778129811, 0.24789194734337, 7.525342283125838, 0.03688814920572669, 6.730051926786799, 0.3131932672999039, 4.532487143295717, 4.150846686218954, 9.179078221264277, 5.098805334592516, 10.52250292428932, 5.024749060437104, 1.067880348732917, 0.04237889411674393, 5.524197570920426, 5.094430115250134, 9.474601810372704, 8.8234455337178, 0.40803013165775065, 2.7848258821928273, 4.304471223164715, 0.022242423860796508, 1.5727054832546101, 4.121503305112782, 1.6036814480034753, 0.8403628783339735, 0.3959314997528379, 0.0948400685663931, 0.4082805469513769, 0.046744805289939496, 0.5249417793314618, 0.13294660495590657, 0.17103373105970487, 1.4176966480545758, 1.52219360820

Enter the number of samples need :  7


Category : 0
[[5.09923554 3.60949414 1.63775874 0.2306014 ]
 [4.94931048 3.99970322 1.30285468 0.29314849]
 [5.20517042 3.11041307 1.55898045 0.29307211]
 [5.22925332 3.36724443 1.69108461 0.29618618]
 [4.90740316 3.89169188 1.30118764 0.29319627]
 [5.03280524 2.84220537 1.71186503 0.11442396]
 [5.12105694 3.37726328 1.5477287  0.22974061]]
Category : 1
[[6.36236334 2.54773268 5.01310172 1.18915429]
 [6.53011839 3.33354591 4.48025599 1.02606893]
 [6.99491207 2.99982666 4.74811197 1.29251116]
 [5.56768875 2.82477699 4.77604785 1.47977829]
 [6.50041538 2.58478936 4.07287195 1.41983994]
 [6.57151499 2.47901312 3.89684886 1.25860103]
 [5.81907354 3.22179622 4.10335299 1.10788941]]
Category : 2
[[6.25016584 2.19252888 4.35001184 2.23417809]
 [6.12453815 2.81024026 4.5505084  2.01524873]
 [5.7772053  2.86900177 5.82877823 2.4943022 ]
 [6.37974312 3.36481229 5.8996665  1.89373003]
 [7.33303832 2.85959583 5.60845124 2.23456866]
 [6.8750861  3.37275204 5.94074938 2.06857911]
 [7.08881606 3.1488